
package MTS.testServer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MtsTestServerService", targetNamespace = "http://testServer.MTS/", wsdlLocation = "http://localhost:8080/services/serverMts?wsdl")
public class MtsTestServerService
    extends Service
{

    private final static URL MTSTESTSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException MTSTESTSERVERSERVICE_EXCEPTION;
    private final static QName MTSTESTSERVERSERVICE_QNAME = new QName("http://testServer.MTS/", "MtsTestServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/services/serverMts?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTSTESTSERVERSERVICE_WSDL_LOCATION = url;
        MTSTESTSERVERSERVICE_EXCEPTION = e;
    }

    public MtsTestServerService() {
        super(__getWsdlLocation(), MTSTESTSERVERSERVICE_QNAME);
    }

    public MtsTestServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MTSTESTSERVERSERVICE_QNAME, features);
    }

    public MtsTestServerService(URL wsdlLocation) {
        super(wsdlLocation, MTSTESTSERVERSERVICE_QNAME);
    }

    public MtsTestServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MTSTESTSERVERSERVICE_QNAME, features);
    }

    public MtsTestServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MtsTestServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MtsTestServer
     */
    @WebEndpoint(name = "MtsTestServerPort")
    public MtsTestServer getMtsTestServerPort() {
        return super.getPort(new QName("http://testServer.MTS/", "MtsTestServerPort"), MtsTestServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MtsTestServer
     */
    @WebEndpoint(name = "MtsTestServerPort")
    public MtsTestServer getMtsTestServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://testServer.MTS/", "MtsTestServerPort"), MtsTestServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MTSTESTSERVERSERVICE_EXCEPTION!= null) {
            throw MTSTESTSERVERSERVICE_EXCEPTION;
        }
        return MTSTESTSERVERSERVICE_WSDL_LOCATION;
    }

}
